print("")

print("#######################")
print("#                     #")
print("# Terminal-Calculator #")
print("#                     #")
print("#######################")

print("")

print("########################")
print("#                      #")
print("#     Optionen:        #")
print("#                      #")
print("#      Plus (1)        #")
print("#      Minus (2)       #")
print("#       Mal (3)        #")
print("#  Geteiltdurch (4)    #")
print("#                      #")
print("########################")